---
title: "CSSR Research Proposal"
author: "Alex Sacharow & Torben Klausa"
date: "October 28, 2016"
output: 
  pdf_document:
    toc: true
    number_sections: true
bibliography:
    -  literature.bib
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)

#Clear Global environment
rm(list=ls())

## Setting Working directory
try(setwd("/home/torben/GIT/Pair_Assignment_2"), silent = TRUE)
try(setwd("D:/Eigene Datein/Dokumente/Uni/Hertie/Materials/Collaborative Social Science Data Analysis/CSSR_Project"), silent = TRUE)

#Collect packages/libraries we need:
packages <- c("readxl")

#install packages if not installed before
for (p in packages) {
  if (p %in% installed.packages()[,1]) {
    require(p, character.only=T)
  }
  else {
    install.packages(p, repos="http://cran.rstudio.com", dependencies = TRUE)
    require(p, character.only=T)
  }
}
rm(p, packages)

# Including the R script
# source("getData.R") # left-over
```

<!--
**************************
***** REQUIRED WORK: *****
**************************
1. We should clean up the readme files. Do we really need one per folder? 
Alex: Seize it down to detailed information (links, date, syntax of filenames)
2. Work count as off 25.10.2016: 1852 (with references 2036)


**************************
*****   OVERVIEW:    *****
**************************
What is our data and where do we get it from?
-- Acute alcohol intoxication - ICD10 Code: F10.0 - GBE-Bund
-- Alcoholic liver disease - ICD10 Code: K70 - GBE-Bund

What are we controlling for?
+- population density - Destatis: "Bevölkerungsdichte: Bundesländer, Stichtag"
-- unemployment rate - Destatis: "Arbeitslose, Arbeitslosenquoten, Gemeldete Arbeitsstellen: Bundesländer, Jahre"
-- youth unemployment - Regionaldatenbank? https://www.statistik.sachsen-anhalt.de/apps/StrukturKompass/indikator/zeitreihe/90
+- state gdp - Destatis: "VGR der Länder - Bruttoinlandsprodukt"
-- Bildungsniveau
   Alcohol sales / Beer sales https://www.destatis.de/GPStatistik/receive/DEHeft_heft_00014241
   https://www.destatis.de/GPStatistik/receive/DESerie_serie_00000146?list=all
-->

# Introduction

<!--
What, Why, How, Basic question, Basic answer
!!!TORBEN TAKES CARE!!!
K70 - Alkoholische Leberkrankheit

-->

In Western Europe alcohol is a commonly used medium for exhilaration. However, it is also known as a (if not *the most harmful*) drug [@Nutt.2010], be it because of its toxic nature itself or the indirect consequences: The consumption of alcoholic beverages may on the one hand lead to behavioural changes and violent acts, as has been indicated by numerous studies [see e.g. @Parker.1993; @Stolle.2009]. On the other hand alcohol, if consumend regularly and over a longer period of time, does severe damage to individuals' health [see e.g. @WHO.2014; Miller.2007]. It is therefore a policy concern not only to identify reasons and motivation for excessive alcohol consumption but also to develop measures to tackle this problem.

It is the aim of this paper to analyse both mentioned dimensions of the *challenge alcohol*. Using the example of all German federal states and time series data for different age groups from 2000 to 2014, we will [1] analyse the possible connection between medical diagnoses of alcohol misuse and possibly explanatory socioeconomic factors like gender, age, unemployment rate, education level, and regional economic performance. For this, we will take both short-term and long-term medical consequences of alcohol misuse into account by examining hospital health records on acute alcohol intoxication as well as on alcoholic liver disease. Besides the socio-economic factors mentioned above, we will [2] test the effect of recent policy measures on the German state level on alcohol consumption. The two cases we are going to examine are [a] the ban on alcohol night sales introduced in 2010 in the state of Baden-Wuerttemberg and [b] the prohibition of alcohol consumption in vehicles and stations of public transport in the federal city state of Hamburg, introduced in 2011.

With this approach, we aim to present an analysis that offers insights into both possible causes for alcohol misuse as well as the efficiency of policy measures designed to counter excessive drinking.

# Related Literature

<!--
!!!TORBEN TAKES CARE!!!
Alex: Ich glaub es sollte vor den Daten teil kommen weil sich das Teile drauf beziehen
-->

Our research proposal is inspired by the work of @Marcus.2015 who analysed *"The Effect of a Ban on Late-Night Off-premise Alcohol Sales on Alcohol-Related Hospital Stays in Germany."* They find that the introduction of the alcohol night sales ban reduces alcohol-related hospitalizations among adolescents and young adults by about seven percent. In our analysis, we will not only try to replicate their work with the publicly available data sets. We are also going to build upon it -- by differenciate between short-term and longer-term effects. The focus on socio-economic explanatory factors like economic performance for the alcohol abuse as such is based upon research done by e.g. @Popovici.2013 and @Ettner.1997. Focusing on the United States, the two studies found inconsistent results: While one sees "a positive and significant effect of unemployment on drinking behaviors and the findings are robust to numerous sensitivity tests" [@Popovici.2013] the other argues that "non-employment significantly reduces both alcohol consumption and dependence symptoms, probably due to an income effect." [@Ettner.1997] For the German case, @Henkel.2000 finds a negative correlation between economic situation and alcohol and nicotine consumption.


# Data

<!--
!!!ALEX TAKES CARE!!!
Structure:
DATA
1. Data Source
1.1. Data gathering
2. Data Advantages
3. Data Disadvantages
4. Our Data Manipulation
Empirical Strategy
1. Basic correlation analysis / linear regression
2. Diff-in-Diff / Time -Series approach
-->


Our research health data origins from the German [hospital diagnosis statistics](https://www.destatis.de/DE/Publikationen/Thematisch/Gesundheit/Krankenhaeuser/DiagnosedatenKrankenhaus.html) from 2000 to 2014, obtained via the [Information System of the Federal Health Monitoring (GBE)](http://www.gbe-bund.de/). The data is reported by hospitals to the statistical bureaus of the respective German states and then aggregated by the [Statistische Bundesamt Destatis](https://www.destatis.de/). The data contains aggregated numbers of hospital diagnoses for each German state by age group, gender and year. The diagnoses are published according to the WHO International Statistical Classification of Diseases and Related Health Problems (ICD-10). 

The data is gathered via the online-interface of the [GBE](http://www.gbe-bund.de/). Unfortunately, the data provider neither provides an API nor a web-scrappable interface. Therefore we download the base tables manually by searching for the respective ICD-10 code, using the malleable tables to gather as much information in a single table as possible and then export them.

To identify alcohol-related health problems we use the diagnose category *F10* (Mental and behavioural disorders due to use of alcohol), more specificly: its subdivision *F10.0* (Acute intoxication) and *F10.2* (Dependence syndrome), and *K70* (Alcoholic liver disease). The diagnoses category *F10.0* essentially captures short term effects of excessive drinking, and can be used as an indicator for binge drinking.[^ICD] The categories *F10.2* and *K70* capture long-term effects of drinking as these diagnoses are consequences of regular drinking.

The advantages of this data is that they reflect a complete survey of all civilian hospitals in Germany for the time-frame of our investigation. Furthermore, the data is not self-reported by patients in interviews but instead consists of the professional diagnoses by a third party, i.e. doctors, which eliminates any problems of possible self-reporting biases. For the case study of Baden-Wuerttemberg's night sale prohibition we do also benefit from the availability of a longer time series as compared to the prior work on the issue by @Marcus.2015. Finally, the state-year aggregation level does allows us to supplement to our analysis a wide variety of other freely available data, e.g. the level of alcohol sales, unemployment rates etc..

However, there are several serious limitations to the data we are using. First of all, the data set can only be exploited with rather strong limitations with the help of more sophisticated methods like panel data analysis. We only have access to data which is reported annually and on the state level.[^FDZ] Hence, for a panel data analysis our scope is limited to 14 years and 16 states, which makes a total of 224 data points for each combination of diagnoses, age group and gender. We still think it is meaningfull to work with and explore the data at hand, as we will on the one hand include simpler but still insightful methods like multiple linear regression. On the other hand, our approach can easily be extended to more fine-grained data if such data becomes available in the future. Still, a second shortcoming is the lack of further information on the patients beyond their age and gender, e.g. socio-economic characteristics.

As already mentioned, our analysis will be supplemented by data from other sources. We are in particular using indicators for the state level. They include the respecitve population, population density, unemployment rates of different age groups, the state GDP and beer sales by state. We are aware of the fact that other alcoholic beverages besides beer probably play a role in the cases under scrutiny. However, with these numbers not available, the beer consumption serves as a proxy for general alcohol consumption in the state. We are collecting the supplementary data from different statistics provided by *Destatis*.

#  Empirical Strategy

We want to make a two stage analysis of short and long-term alcohol-related hospitalizations (ARH)[^ARH]. We will start with a multiple regression for a better understanding of factors correlated to high rates of hospitalizaton for alcohol-related reasons. This analysis shall show how socio-economic characteristics of states are correlated to the number of ARH. The simple multiple regression model for one year t looks like this:
<!--
Question: Should we make the regression for one year, for the average of the whole period, or for each time-state pair?
Selecting one year has the advantage that the data will be purely cross-sectional and there are no time-effects.
If we make the regression on each time-state pair we have a much larger number of observations, but we might have time-effects which cause problems.

T:
I am thinking it might be cool to do it for all state/year pairs and to present the results (significance levels only) in a table directly next to each other so we can see whether it "kind of" works at one glance. What do you think?
-->
\begin{equation}
    ARH_s = \alpha_0 + \alpha_1 \cdot GDP_s + \alpha_2 \cdot UR_s + \alpha_3 \cdot B_s + \alpha_4 \cdot PD_s + \epsilon_s
\end{equation}

where $GDP$ stands for the states GDP level, $UR$ for the states unemployment rate, $B$ for the beer consumption in the state and $PD$ for the population density. The regression will be conducted for the aggregated number for all age groups and than for specific age-groups making use of the age-group specific unemployment rate.
Based on the idea that individuals adapt to their circumstances and are more reactive to changes than to actual levels we will analysis ARH difference:

\begin{equation}
   \Delta ARH_{s,t} = \beta_1 \cdot \Delta GDP_{s, t} + \beta_2 \cdot UR_{s, t} + \beta_3 \cdot \Delta B_{s, t} + \alpha_4 \cdot PD_s + \epsilon_{s,t}
\end{equation}

In contrast to the multiple regression on levels, the difference approach highlights how *changes* in hospitalizations are correlated to *changes* in the socio-economic factors used as independend variables.

In the second step of our analysis, we are looking at the effect of the night sales ban on alcohol in Baden-Wuerttemberg. To measure the effect of the ban we use the difference-in-difference (DD) approach. As the ban was only introduced in Baden-Wuerttemberg, this state will be the treatment group. All other states are in the control group. This distinction can be justified by the fact that most alcohol regulation is done on the federal level with the exception of sales hour regulation and campaigns.[^TCG] The ban was introduced in 2010, which is captured by the treatment dummy. We further assume there are no dynamic effects, which is reasonable as patients are registered when their treatment begins:[^REG] 

<!--
A: I am not sure whether to include coefficients before POST and BW because this seems to be common practice when using DD. But this seems only to be the case of DD is applied to the 2 period case. Since we do have many cases we need to conclude a coefficient as we are using multiple regression in the end. 

On having multiple periods in DD: 
http://stats.stackexchange.com/questions/76058/specifying-a-difference-in-differences-model-with-multiple-time-periods

On adding covariantes (4th equastion) see http://stats.stackexchange.com/questions/110874/control-variables-difference-in-difference
-->

<!--
********OLD********
\begin{equation}
   ARH_{s,t} = \gamma_0 + \gamma_1 \cdot BAN_{s,t} + \gamma_2 \cdot POST_t + \gamma_4 \cdot BW_s + \epsilon_{s,t}
\end{equation}
-->

\begin{equation}
   ARH_{s,t} = \gamma_0 + \gamma_1 \cdot dBW_{s} + \gamma_2 \cdot dYEAR_t + \gamma_4 \cdot dBAN_{s,t} + \epsilon_{s,t}
\end{equation}

where $dBW$ is a dummy variable to indicate the treatmeant group (i.e. the state of Baden-Württemberg), $dYEAR$ a time dummy and $dBAN$ a dummy for the night-sale-prohibition ($= 1$ for Baden-Württemberg from 2010 on). Since were are re-engineering @Marcus.2015 here, we will limit the DD application to ARH by young people (15-25). To check for further robustness of the results, we are comparing short-term ARH (F10.0), which should show an effect according to @Marcus.2015, and long-term ARH (K70/F10.2), which should not be affected in the short term by the treatment.

As the DD approach crucially depends on the common trend assumption, it is advisable to include control variables to capture possible trends affecting treatment and control group differently. We control for youth unemployment ($YUR$) as an economic factor and $B$ as a proxy variable for the general alcohol consumption.

<!--
********OLD********
\begin{equation}
  ARH_{s,t} = \delta_0 + \delta_1 \cdot BAN_{s,t} + \delta_2 \cdot POST_{t} + \delta_3 \cdot BW_s + \delta_4 \cdot YUR_s + \epsilon_{s,t}
\end{equation}
-->
\begin{equation}
  ARH_{s,t} = \delta_0 + \delta_1 \cdot dBW_{s} + \delta_2 \cdot dYEAR_t + \delta_3 \cdot dBAN_{s,t} + \delta_4 \cdot YUR_{s,t} + \delta_4 \cdot B_{s,t} + \epsilon_{s,t}
\end{equation}


Finally, we are refining our DD approach further by turning it into a panel and splitting up the control group. This is the final version of the model, but we expect it to generate less insightful results as we (with all states seperately) have comparably few data points (due to comparably little money to invest in data...).

<!--
********OLD********
\begin{equation}
  ARH_{s,t} = \theta_0 + \theta_1 \cdot BAN_{s,t} + FED_{t} +  c_s + \theta_2 \cdot YUR_s + \epsilon_{s,t}
\end{equation}
-->
\begin{equation}
  ARH_{s,t} = \theta_0 + \theta_1 \cdot dSTATES_{s} + \theta_2 dYEAR_t + \theta_3 \cdot dBAN_{s,t} + \theta_4 \cdot YUR_{s,t} + \theta_5 \cdot B_{s,t} + \epsilon_{s,t}
\end{equation}

where $dSTATES$ now is a dummy variable not only separating Baden-Württemberg (treatment group) from the other 15 states (non-treatment group) but a dummy for all states.
This model includes time-invariant state fixed effects $dSTATES$, and time fixed effects $dYEAR$ affecting all states, e.g. a change in a federal law. <!-- T: What do you mean by the following sentence? "This model can be estimated by using dummies for the time-periods and first-differencing or fixed-effects to address the unobserved heterogeneity of states." --> 


# References


[^ICD]: In contrast to @Marcus.2015 and @Wicki.2011 we do not include T51 (Intoxination due to alcohol) as its covers the consumption of pure ethanol and its number are relatively small. 
[^FDZ]: In principle there is more fine-grained data available, even down to the individual level. However, the access to the data requires using the paid services by [forschungsdatenzentrum.de](http://www.forschungsdatenzentrum.de/) which is out of our students' budget.
[^ARH]: ARH is normalized by the state population and denoted in hospitalizations per 100,000 inhabitants.
[^TCG]: The night-sale ban in Baden-Wuerttenberg has been the most prominent alcohol policy in 2010. There have also been general changes to opening hours as during this time the competency was transfered to the states and media campaigns. As we only have annual data we are not fully able to distnguish between these treatments, but we assume that they are outweigthed by the night-sales ban.
[^REG]: Even if they would be registered in consecutive reporting periods, the stay of patients for short-term ARH (*F10.0*) is in average 2,1 days and for long-term ARH 10,7 days (*K70*) and 11,4 days (*F10.2*) in 2014 making the dynamic effect insignificantly small.